name = "metamethods/typed"
version = "0.9.1"
description = "luau runtime type validation library"
authors = ["metamethods"]
repository = "https://github.com/metamethods/typed"
license = "MIT"
includes = [
  "pesde.toml",
  "README.md",
  "LICENSE",
  "lib/**/*.luau",
]

[peer_dependencies]
typed_core = { workspace = "metamethods/typed_core", version = "^0.1.0" }

[target]
environment = "luau"
lib = "lib/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
