name = "metamethods/typed_core"
version = "0.1.0"
includes = [
  "pesde.toml",
  "README.md",
  "LICENSE",
  "lib/**/*.luau",
]

[target]
environment = "luau"
lib = "lib/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
