name: release

on:
    push:
        tags:
            - "v*"

permissions:
    contents: write

jobs:
    release:
        name: release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: CompeyDev/setup-rokit@v0.2.1
            - run: rojo build --output typed.rbxm
            - uses: softprops/action-gh-release@v3
              with:
                  name: typed ${{ github.ref_name }}
                  generate_release_notes: true
                  files: typed.rbxm
    publish-pesde:
        name: publish pesde
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: lumin-org/setup-pesde@v0.4.1
            - run: pesde install
            - run: pesde auth login --token "${{ secrets.PESDE_TOKEN }}"
            - run: pesde publish --yes
